name:                modeling
version:             0.1.0
github:              "githubuser/modeling"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "(c) 2019 Author name here"

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/githubuser/modeling#readme>

dependencies:
- base >= 4.11 && < 5
- aeson
- bytestring
- containers
- data-fix
- generic-lens
- lens
- mtl
- newtype-generics
# - pretty-simple
- text
- transformers
- unordered-containers
# - vector
- yaml

default-extensions:
  - ConstraintKinds
  - DeriveFunctor
  - DeriveFoldable
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - KindSignatures
  - NamedFieldPuns
  - OverloadedStrings
  - Rank2Types
  - RecordWildCards
  - StandaloneDeriving
  - TypeFamilies

library:
  source-dirs: src

tests:
  modeling-test:
    main:                Tasty.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - modeling
    - heredoc
    - tasty
    - tasty-discover
    - tasty-hunit
